// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(VehicleBatteryMarketDbContext))]
    partial class VehicleBatteryMarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Auction", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionId"));

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AuctionStart")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BuyNowPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CurrentWinnerId")
                        .HasColumnType("int");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("AuctionId")
                        .HasName("PK__Auctions__51004A4CE23C27D6");

                    b.HasIndex(new[] { "CurrentWinnerId" }, "IX_Auctions_CurrentWinnerId");

                    b.HasIndex(new[] { "ListingId" }, "UQ__Auctions__BF3EBED14F781AB9")
                        .IsUnique();

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("DAL.Models.BatteryDetail", b =>
                {
                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CapacityWh")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Voltage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ListingId")
                        .HasName("PK__BatteryD__BF3EBED00E27DE04");

                    b.ToTable("BatteryDetails");
                });

            modelBuilder.Entity("DAL.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int>("BidderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("BidId")
                        .HasName("PK__Bids__4A733D92BE64A057");

                    b.HasIndex(new[] { "AuctionId" }, "IX_Bids_AuctionId");

                    b.HasIndex(new[] { "BidderId" }, "IX_Bids_BidderId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("DAL.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B72B95DD5");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DAL.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("ContractData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<bool?>("SignedByBuyer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("SignedBySeller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ContractId")
                        .HasName("PK__Contract__C90D346951CCB53F");

                    b.HasIndex(new[] { "OrderId" }, "UQ__Contract__C3905BCEA8E37823")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("DAL.Models.EbikeDetail", b =>
                {
                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<decimal?>("BatteryVoltage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FrameSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MileageKm")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MotorPowerW")
                        .HasColumnType("int");

                    b.Property<int?>("RangeKm")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("YearOfManufacture")
                        .HasColumnType("int");

                    b.HasKey("ListingId")
                        .HasName("PK__EBikeDet__BF3EBED023E3ECCF");

                    b.ToTable("EBikeDetails", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__CE74FAD53EB30588");

                    b.HasIndex(new[] { "ListingId" }, "IX_Favorites_ListingId");

                    b.HasIndex(new[] { "MemberId", "ListingId" }, "UQ_Fav")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("DAL.Models.Listing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ListingStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("draft");

                    b.Property<string>("ListingType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("buy_now");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("ListingId")
                        .HasName("PK__Listings__BF3EBED077549B47");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "MemberId" }, "IX_Listings_MemberId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("DAL.Models.ListingImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ImageId")
                        .HasName("PK__ListingI__7516F70CA5400FBD");

                    b.HasIndex(new[] { "ListingId" }, "IX_ListingImages_ListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("DAL.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("MemberId")
                        .HasName("PK__Members__0CF04B18D8AC7003");

                    b.HasIndex(new[] { "Phone" }, "UQ__Members__5C7E359E65C61BDC")
                        .IsUnique()
                        .HasFilter("([Phone] IS NOT NULL)");

                    b.HasIndex(new[] { "Email" }, "UQ__Members__A9D10534F235FD87")
                        .IsUnique()
                        .HasFilter("([Email] IS NOT NULL)");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("DAL.Models.MemberAuth", b =>
                {
                    b.Property<int>("MemberAuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberAuthId"));

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MemberAuthId")
                        .HasName("PK__MemberAu__0B93795FA7668681");

                    b.HasIndex(new[] { "MemberId" }, "UQ__MemberAu__0CF04B199F7340A5")
                        .IsUnique();

                    b.ToTable("MemberAuths");
                });

            modelBuilder.Entity("DAL.Models.MemberProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId")
                        .HasName("PK__MemberPr__290C88E46386368A");

                    b.HasIndex(new[] { "MemberId" }, "UQ__MemberPr__0CF04B1949A28C36")
                        .IsUnique();

                    b.ToTable("MemberProfiles");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BCF6516D58F");

                    b.HasIndex(new[] { "BuyerId" }, "IX_Orders_BuyerId");

                    b.HasIndex(new[] { "ListingId" }, "IX_Orders_ListingId");

                    b.HasIndex(new[] { "SellerId" }, "IX_Orders_SellerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DAL.Models.PayOSPayment", b =>
                {
                    b.Property<int>("PayOspaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PayOSPaymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayOspaymentId"));

                    b.Property<string>("AccountName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Qrcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QRCode");

                    b.Property<string>("Reference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PayOspaymentId")
                        .HasName("PK__PayOSPayments__89738AA7D4F7456E");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_PayOSPayments_CreatedAt");

                    b.HasIndex(new[] { "PaymentId" }, "IX_PayOSPayments_PaymentId");

                    b.ToTable("PayOSPayments", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderRef")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A388666DF25");

                    b.HasIndex(new[] { "OrderId" }, "IX_Payments_OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DAL.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("RevieweeId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79CEBA33A37E");

                    b.HasIndex(new[] { "OrderId" }, "IX_Reviews_OrderId");

                    b.HasIndex(new[] { "RevieweeId" }, "IX_Reviews_RevieweeId");

                    b.HasIndex(new[] { "ReviewerId" }, "IX_Reviews_ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DAL.Models.TransactionsLog", b =>
                {
                    b.Property<int>("TxnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TxnId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ListingId")
                        .HasColumnType("int");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("TxnId")
                        .HasName("PK__Transact__C196085431C8A18C");

                    b.HasIndex(new[] { "ListingId" }, "IX_TransactionsLog_ListingId");

                    b.HasIndex(new[] { "MemberId" }, "IX_TransactionsLog_MemberId");

                    b.HasIndex(new[] { "OrderId" }, "IX_TransactionsLog_OrderId");

                    b.ToTable("TransactionsLog", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Auction", b =>
                {
                    b.HasOne("DAL.Models.Member", "CurrentWinner")
                        .WithMany("Auctions")
                        .HasForeignKey("CurrentWinnerId")
                        .HasConstraintName("FK__Auctions__Curren__656C112C");

                    b.HasOne("DAL.Models.Listing", "Listing")
                        .WithOne("Auction")
                        .HasForeignKey("DAL.Models.Auction", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Auctions__Listin__6477ECF3");

                    b.Navigation("CurrentWinner");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("DAL.Models.BatteryDetail", b =>
                {
                    b.HasOne("DAL.Models.Listing", "Listing")
                        .WithOne("BatteryDetail")
                        .HasForeignKey("DAL.Models.BatteryDetail", "ListingId")
                        .IsRequired()
                        .HasConstraintName("FK__BatteryDe__Listi__04E4BC85");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("DAL.Models.Bid", b =>
                {
                    b.HasOne("DAL.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Bids__AuctionId__6A30C649");

                    b.HasOne("DAL.Models.Member", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .IsRequired()
                        .HasConstraintName("FK__Bids__BidderId__6B24EA82");

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("DAL.Models.Contract", b =>
                {
                    b.HasOne("DAL.Models.Order", "Order")
                        .WithOne("Contract")
                        .HasForeignKey("DAL.Models.Contract", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Contracts__Order__5DCAEF64");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.EbikeDetail", b =>
                {
                    b.HasOne("DAL.Models.Listing", "Listing")
                        .WithOne("EbikeDetail")
                        .HasForeignKey("DAL.Models.EbikeDetail", "ListingId")
                        .IsRequired()
                        .HasConstraintName("FK__EBikeDeta__Listi__05D8E0BE");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("DAL.Models.Favorite", b =>
                {
                    b.HasOne("DAL.Models.Listing", "Listing")
                        .WithMany("Favorites")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Fav_Listing");

                    b.HasOne("DAL.Models.Member", "Member")
                        .WithMany("Favorites")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Fav_Member");

                    b.Navigation("Listing");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DAL.Models.Listing", b =>
                {
                    b.HasOne("DAL.Models.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Listings_Categories");

                    b.HasOne("DAL.Models.Member", "Member")
                        .WithMany("Listings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Listings__Member__47DBAE45");

                    b.Navigation("Category");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DAL.Models.ListingImage", b =>
                {
                    b.HasOne("DAL.Models.Listing", "Listing")
                        .WithMany("ListingImages")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ListingIm__Listi__4D94879B");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("DAL.Models.MemberAuth", b =>
                {
                    b.HasOne("DAL.Models.Member", "Member")
                        .WithOne("MemberAuth")
                        .HasForeignKey("DAL.Models.MemberAuth", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MemberAut__Membe__3F466844");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DAL.Models.MemberProfile", b =>
                {
                    b.HasOne("DAL.Models.Member", "Member")
                        .WithOne("MemberProfile")
                        .HasForeignKey("DAL.Models.MemberProfile", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MemberPro__Membe__440B1D61");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.Member", "Buyer")
                        .WithMany("OrderBuyers")
                        .HasForeignKey("BuyerId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__BuyerId__52593CB8");

                    b.HasOne("DAL.Models.Listing", "Listing")
                        .WithMany("Orders")
                        .HasForeignKey("ListingId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__ListingI__5165187F");

                    b.HasOne("DAL.Models.Member", "Seller")
                        .WithMany("OrderSellers")
                        .HasForeignKey("SellerId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__SellerId__534D60F1");

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("DAL.Models.PayOSPayment", b =>
                {
                    b.HasOne("DAL.Models.Payment", "Payment")
                        .WithMany("PayOspayments")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PayOSPayments_Payment");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("DAL.Models.Payment", b =>
                {
                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Payments__OrderI__5812160E");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.Review", b =>
                {
                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Reviews__OrderId__76969D2E");

                    b.HasOne("DAL.Models.Member", "Reviewee")
                        .WithMany("ReviewReviewees")
                        .HasForeignKey("RevieweeId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__RevieweeId__75A278F5");

                    b.HasOne("DAL.Models.Member", "Reviewer")
                        .WithMany("ReviewReviewers")
                        .HasForeignKey("ReviewerId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__ReviewerId__74AE54BC");

                    b.Navigation("Order");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("DAL.Models.TransactionsLog", b =>
                {
                    b.HasOne("DAL.Models.Listing", "Listing")
                        .WithMany("TransactionsLogs")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK__Transacti__Listi__7C4F7684");

                    b.HasOne("DAL.Models.Member", "Member")
                        .WithMany("TransactionsLogs")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK__Transacti__Membe__7B5B524B");

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("TransactionsLogs")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Transacti__Order__7D439ABD");

                    b.Navigation("Listing");

                    b.Navigation("Member");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("DAL.Models.Category", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("DAL.Models.Listing", b =>
                {
                    b.Navigation("Auction");

                    b.Navigation("BatteryDetail");

                    b.Navigation("EbikeDetail");

                    b.Navigation("Favorites");

                    b.Navigation("ListingImages");

                    b.Navigation("Orders");

                    b.Navigation("TransactionsLogs");
                });

            modelBuilder.Entity("DAL.Models.Member", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");

                    b.Navigation("Favorites");

                    b.Navigation("Listings");

                    b.Navigation("MemberAuth");

                    b.Navigation("MemberProfile");

                    b.Navigation("OrderBuyers");

                    b.Navigation("OrderSellers");

                    b.Navigation("ReviewReviewees");

                    b.Navigation("ReviewReviewers");

                    b.Navigation("TransactionsLogs");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("TransactionsLogs");
                });

            modelBuilder.Entity("DAL.Models.Payment", b =>
                {
                    b.Navigation("PayOspayments");
                });
#pragma warning restore 612, 618
        }
    }
}
